<?php
    /**
     * Project Name:    Wingman — Locator — Cache Manager
     * Created by:      Angel Politis
     * Creation Date:   Feb 25 2026
     * Last Modified:   Mar 14 2026
     *
     * Copyright (c) 2026-2026 Angel Politis <info@angelpolitis.com>
     * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
     * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
     */
    # Use the Locator namespace.
    namespace Wingman\Locator;

    # Import the following classes to the current scope.
    use Wingman\Locator\Bridge\Cortex\Attributes\Configurable;
    use Wingman\Locator\Bridge\Cortex\Configuration;

    /**
     * Manages caching of discovery results to improve performance and reduce redundant operations.
     * @package Wingman\Locator
     * @author Angel Politis <info@angelpolitis.com>
     * @since 1.0
     */
    class CacheManager {
        /**
         * The configuration key for the cache file path.
         * @var string
         */
        public const string FILE_KEY = "locator.caching.file";

        /**
         * The configuration key for the cache TTL.
         * @var string
         */
        public const string TTL_KEY = "locator.caching.ttl";

        /**
         * The file path where the cache will be stored.
         * @var string
         */
        #[Configurable(self::FILE_KEY, "The file path to store the locator cache.")]
        protected string $filePath = __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "temp" . DIRECTORY_SEPARATOR . "cache.php";

        /**
         * The maximum age of a valid cache entry in seconds. A value of `0` disables TTL validation and keeps the cache until explicitly cleared.
         * @var int
         */
        #[Configurable(self::TTL_KEY, "The maximum age of the discovery cache in seconds. Set to 0 to disable TTL.")]
        protected int $maxAge = 0;

        /**
         * Creates a new cache manager.
         * @param array|Configuration $config A flat configuration map using dot-notation keys, or a Cortex `Configuration` instance.
         * Supported keys: `CacheManager::FILE_KEY`, `CacheManager::TTL_KEY`.
         */
        public function __construct (array|Configuration $config = []) {
            Configuration::hydrate($this, $config);
        }

        /**
         * Clears the cache by deleting the cache file.
         * @return bool Whether the cache was successfully cleared.
         */
        public function clear () : bool {
            return file_exists($this->filePath) ? unlink($this->filePath) : true;
        }

        /**
         * Loads the cached state if available and not yet stale.
         * Returns `null` when the cache file does not exist, contains invalid data, or has exceeded the configured TTL.
         * @return array|null The cached data, or `null` if unavailable or stale.
         */
        public function load () : ?array {
            if (!file_exists($this->filePath)) return null;

            $data = include $this->filePath;

            if (!is_array($data)) return null;

            if ($this->maxAge > 0 && isset($data["timestamp"]) && (time() - $data["timestamp"]) > $this->maxAge) {
                return null;
            }

            return $data;
        }

        /**
         * Persists the current state of discovery.
         * @param array $manifestData The manifest data to save.
         * @param array $scannedRoots The scanned roots to save.
         * @return bool Whether the data was successfully saved.
         */
        public function save (array $manifestData, array $scannedRoots) : bool {
            $manifests = [];
            foreach ($manifestData as $manifest) {
                $manifests[] = $manifest->dehydrate();
            }

            $data = [
                "manifests" => $manifests,
                "roots" => $scannedRoots,
                "timestamp" => time()
            ];

            $content = "<?php\n# Generated by Wingman Locator - " . date("Y-m-d H:i:s") . "\n";
            $content .= "return " . var_export($data, true) . ";";
            
            if (!is_dir(dirname($this->filePath))) {
                mkdir(dirname($this->filePath), 0755, true);
            }

            return file_put_contents($this->filePath, $content, LOCK_EX) !== false;
        }
    }
?>